"""empty message

Revision ID: 29d1050b479d
Revises: 64b68f16015c
Create Date: 2023-03-18 00:54:25.307093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d1050b479d'
down_revision = '64b68f16015c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_grade')
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpa', sa.Float(), nullable=True))
        batch_op.alter_column('grade',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.drop_column('cgpa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cgpa', sa.FLOAT(), nullable=False))
        batch_op.alter_column('grade',
               existing_type=sa.String(length=10),
               type_=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('gpa')

    op.create_table('_alembic_tmp_grade',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('grade', sa.VARCHAR(length=10), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('gpa', sa.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
