"""empty message

Revision ID: 64b68f16015c
Revises: a82cf945892b
Create Date: 2023-03-18 00:51:25.108841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b68f16015c'
down_revision = 'a82cf945892b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gpa', sa.Float(), nullable=False))
        batch_op.alter_column('grade',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_column('cgpa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cgpa', sa.FLOAT(), nullable=False))
        batch_op.alter_column('grade',
               existing_type=sa.String(length=10),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('gpa')

    # ### end Alembic commands ###
